net:mdio:mdio-mux: Fix build error: no member named 'read_c45'/'write_c45'
Build error:
mdio-mux.c:72:19: error: no member named 'read_c45' in 'struct mii_bus'
mdio-mux.c:119:19: error: no member named 'write_c45' in 'struct mii_bus'

The commit 005dc5699ba43c8996ad003fa1755e033130157e defines
functions for read_c45/write_c45 to point to, but read_c45/write_c45
function pointers are declared under ifndef CONFIG_IMX_GKI_FIX condition,
introduced by the commit 45e61bc21e3ed0ff030abce1e9025e00704a48f3,

To fix the error applying the same approach as in the above commit, assign and call
function pointers under the same condition (ifndef CONFIG_IMX_GKI_FIX)
Signed-off-by: Natalia Kovalenko <natasha.k@variscite.com>